server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: orders-service
          uri: http://orders-service:8081
          predicates:
            - Path=/api/orders/**
        - id: payments-service
          uri: http://payments-service:8082
          predicates:
            - Path=/api/payments/**